/**
 * ชุดไอคอนคัดสรรสำหรับโปรเจกต์ (lucide) — ค้นได้ด้วยคีย์เวิร์ดไทย/อังกฤษ
 * name = kebab-case (เก็บใน DB เป็น `lucide:<name>`) · ใช้ทั้ง picker และ <ProjectIcon>
 * ทุกชื่อ verify แล้วว่ามีจริงใน lucide-react ที่ติดตั้ง (กัน build พัง)
 */
import {
  Anchor, Apple, AppWindow, AtSign, Baby, Banknote, BarChart3, Beef, Beer, Bell, Bike, Binary,
  Bookmark, Bot, Boxes, Brain, Briefcase, Brush, Bug, Building, Building2, Bus, Cake, Calculator,
  Calendar, Camera, Car, Carrot, CheckCircle2, Church, Clipboard, ClipboardList, Cloud, Code, Cog,
  Coffee, Coins, Compass, Component, Container, CreditCard, Croissant, Crown, Cpu, Database, Download,
  Drumstick, Dumbbell, Eye, Factory, FileCode, FileText, Film, Fish, Flag, Flower2, Folder,
  FolderGit2, FolderOpen, Gamepad2, Gem, Gift, GitBranch, Globe, GraduationCap, Hammer, Headphones,
  Heart, Home, Hospital, IceCream, Image, Inbox, Key, Landmark, Layers, Layout, LayoutDashboard,
  LayoutGrid, Leaf, Lightbulb, LineChart, Link2, Lock, Mail, Map, MapPin, Megaphone, MessageCircle,
  MessageSquare, Mic, MonitorSmartphone, Moon, Music, Network, Newspaper, Package, Paintbrush,
  Palette, PanelsTopLeft, PawPrint, PenTool, Phone, PieChart, Pizza, Plane, Puzzle, Receipt, Rocket,
  Ruler,
  Salad, Scale, School, Scissors, Search, Send, Server, Settings, Share2, ShieldCheck, Ship, Shirt,
  ShoppingBag, ShoppingCart, Smartphone, Soup, Sparkles, Star, Stethoscope, Store, Sun, Tag, Tags, Target,
  Terminal, Train, TreePine, Trees, Trophy, Truck, Upload, Users, Utensils, Video, Wallet,
  Warehouse, Webhook, Wifi, Wine, Wrench, Zap, type LucideIcon,
} from 'lucide-react'

export interface ProjectIconDef {
  name: string // kebab-case (เก็บใน DB)
  Icon: LucideIcon
  keywords: string // ไทย+อังกฤษ สำหรับค้น
}

export const PROJECT_ICONS: ProjectIconDef[] = [
  // ธุรกิจ / องค์กร
  { name: 'building-2', Icon: Building2, keywords: 'office company องค์กร บริษัท อาคาร ตึก สำนักงาน' },
  { name: 'building', Icon: Building, keywords: 'office อาคาร ตึก สำนักงาน' },
  { name: 'briefcase', Icon: Briefcase, keywords: 'work business งาน กระเป๋า ธุรกิจ' },
  { name: 'store', Icon: Store, keywords: 'shop ร้าน ร้านค้า หน้าร้าน' },
  { name: 'factory', Icon: Factory, keywords: 'industry โรงงาน อุตสาหกรรม' },
  { name: 'warehouse', Icon: Warehouse, keywords: 'storage โกดัง คลังสินค้า' },
  { name: 'landmark', Icon: Landmark, keywords: 'bank government ธนาคาร ราชการ สถาบัน' },
  { name: 'home', Icon: Home, keywords: 'house บ้าน หน้าแรก อสังหา' },
  { name: 'hospital', Icon: Hospital, keywords: 'clinic โรงพยาบาล คลินิก สุขภาพ' },
  { name: 'school', Icon: School, keywords: 'education โรงเรียน การศึกษา' },
  { name: 'church', Icon: Church, keywords: 'temple วัด โบสถ์ ศาสนา' },
  { name: 'graduation-cap', Icon: GraduationCap, keywords: 'education เรียน การศึกษา จบ มหาวิทยาลัย' },

  // เว็บ / เทคโนโลยี
  { name: 'globe', Icon: Globe, keywords: 'web website เว็บ เว็บไซต์ โลก อินเทอร์เน็ต' },
  { name: 'app-window', Icon: AppWindow, keywords: 'web app เว็บแอป หน้าต่าง โปรแกรม' },
  { name: 'monitor-smartphone', Icon: MonitorSmartphone, keywords: 'responsive web mobile เว็บ มือถือ' },
  { name: 'smartphone', Icon: Smartphone, keywords: 'mobile app แอป มือถือ' },
  { name: 'code', Icon: Code, keywords: 'dev develop โค้ด เขียนโปรแกรม พัฒนา' },
  { name: 'file-code', Icon: FileCode, keywords: 'source โค้ด ไฟล์ สคริปต์' },
  { name: 'terminal', Icon: Terminal, keywords: 'cli console เทอร์มินอล คำสั่ง' },
  { name: 'git-branch', Icon: GitBranch, keywords: 'git version branch เวอร์ชัน' },
  { name: 'folder-git-2', Icon: FolderGit2, keywords: 'repo git โปรเจกต์ repository' },
  { name: 'server', Icon: Server, keywords: 'hosting เซิร์ฟเวอร์ โฮสติ้ง' },
  { name: 'database', Icon: Database, keywords: 'db data ฐานข้อมูล ข้อมูล' },
  { name: 'cloud', Icon: Cloud, keywords: 'cloud คลาวด์ โฮสติ้ง' },
  { name: 'cpu', Icon: Cpu, keywords: 'chip server ชิป ประมวลผล' },
  { name: 'network', Icon: Network, keywords: 'system เครือข่าย ระบบ' },
  { name: 'webhook', Icon: Webhook, keywords: 'api integration เชื่อมต่อ' },
  { name: 'binary', Icon: Binary, keywords: 'data code ข้อมูล' },
  { name: 'wifi', Icon: Wifi, keywords: 'internet network เน็ต อินเทอร์เน็ต' },
  { name: 'bot', Icon: Bot, keywords: 'ai chatbot บอท เอไอ' },
  { name: 'brain', Icon: Brain, keywords: 'ai ml สมอง เอไอ' },
  { name: 'shield-check', Icon: ShieldCheck, keywords: 'security ปลอดภัย ความปลอดภัย ssl' },
  { name: 'lock', Icon: Lock, keywords: 'security ล็อก ปลอดภัย รหัส' },
  { name: 'key', Icon: Key, keywords: 'password api key กุญแจ รหัส' },
  { name: 'bug', Icon: Bug, keywords: 'qa test บั๊ก ทดสอบ' },

  // ดีไซน์ / สื่อ
  { name: 'palette', Icon: Palette, keywords: 'design จานสี ออกแบบ ดีไซน์' },
  { name: 'brush', Icon: Brush, keywords: 'design paint แปรง วาด ออกแบบ' },
  { name: 'paintbrush', Icon: Paintbrush, keywords: 'design paint พู่กัน ทาสี ออกแบบ' },
  { name: 'pen-tool', Icon: PenTool, keywords: 'design vector ปากกา เวกเตอร์ ออกแบบ' },
  { name: 'layout', Icon: Layout, keywords: 'design ui เลย์เอาต์ หน้าจอ' },
  { name: 'layout-grid', Icon: LayoutGrid, keywords: 'grid ui ตาราง เลย์เอาต์' },
  { name: 'layout-dashboard', Icon: LayoutDashboard, keywords: 'dashboard แดชบอร์ด หน้าจอ' },
  { name: 'panels-top-left', Icon: PanelsTopLeft, keywords: 'ui panel เลย์เอาต์ หน้าจอ' },
  { name: 'component', Icon: Component, keywords: 'ui design ส่วนประกอบ คอมโพเนนต์' },
  { name: 'puzzle', Icon: Puzzle, keywords: 'plugin module ปลั๊กอิน ต่อ' },
  { name: 'layers', Icon: Layers, keywords: 'design layer เลเยอร์ ชั้น' },
  { name: 'image', Icon: Image, keywords: 'photo picture รูป ภาพ' },
  { name: 'camera', Icon: Camera, keywords: 'photo กล้อง ถ่ายรูป' },
  { name: 'video', Icon: Video, keywords: 'movie วิดีโอ คลิป' },
  { name: 'film', Icon: Film, keywords: 'movie หนัง ภาพยนตร์ วิดีโอ' },
  { name: 'music', Icon: Music, keywords: 'audio song เพลง เสียง ดนตรี' },
  { name: 'mic', Icon: Mic, keywords: 'podcast voice ไมค์ บันทึกเสียง' },
  { name: 'headphones', Icon: Headphones, keywords: 'audio หูฟัง เสียง' },
  { name: 'newspaper', Icon: Newspaper, keywords: 'news blog ข่าว บทความ สื่อ นิตยสาร' },
  { name: 'megaphone', Icon: Megaphone, keywords: 'marketing ad โฆษณา การตลาด ประกาศ' },
  { name: 'gamepad-2', Icon: Gamepad2, keywords: 'game เกม' },

  // อีคอมเมิร์ซ / การเงิน
  { name: 'shopping-cart', Icon: ShoppingCart, keywords: 'ecommerce shop ตะกร้า ร้านค้า ขายของ' },
  { name: 'shopping-bag', Icon: ShoppingBag, keywords: 'ecommerce shop ถุง ช้อปปิ้ง ซื้อ' },
  { name: 'package', Icon: Package, keywords: 'product box สินค้า กล่อง พัสดุ' },
  { name: 'boxes', Icon: Boxes, keywords: 'inventory stock สต็อก สินค้า คลัง' },
  { name: 'container', Icon: Container, keywords: 'shipping ตู้ ขนส่ง' },
  { name: 'truck', Icon: Truck, keywords: 'delivery shipping ส่งของ ขนส่ง รถบรรทุก' },
  { name: 'credit-card', Icon: CreditCard, keywords: 'payment บัตร จ่ายเงิน ชำระ' },
  { name: 'wallet', Icon: Wallet, keywords: 'money กระเป๋าเงิน เงิน' },
  { name: 'banknote', Icon: Banknote, keywords: 'money cash ธนบัตร เงินสด' },
  { name: 'coins', Icon: Coins, keywords: 'money เหรียญ เงิน' },
  { name: 'receipt', Icon: Receipt, keywords: 'invoice bill ใบเสร็จ บิล ใบแจ้งหนี้' },
  { name: 'calculator', Icon: Calculator, keywords: 'accounting เครื่องคิดเลข บัญชี' },
  { name: 'bar-chart-3', Icon: BarChart3, keywords: 'analytics report กราฟ สถิติ รายงาน' },
  { name: 'line-chart', Icon: LineChart, keywords: 'analytics trend กราฟเส้น แนวโน้ม' },
  { name: 'pie-chart', Icon: PieChart, keywords: 'analytics กราฟวงกลม สัดส่วน' },
  { name: 'target', Icon: Target, keywords: 'goal kpi เป้าหมาย' },
  { name: 'trophy', Icon: Trophy, keywords: 'win award ถ้วยรางวัล ชนะ' },

  // ติดต่อสื่อสาร / ออฟฟิศ
  { name: 'mail', Icon: Mail, keywords: 'email อีเมล จดหมาย' },
  { name: 'inbox', Icon: Inbox, keywords: 'email กล่องจดหมาย' },
  { name: 'send', Icon: Send, keywords: 'message ส่ง' },
  { name: 'at-sign', Icon: AtSign, keywords: 'email mention แอท' },
  { name: 'message-square', Icon: MessageSquare, keywords: 'chat comment แชท ข้อความ' },
  { name: 'message-circle', Icon: MessageCircle, keywords: 'chat แชท ข้อความ คุย' },
  { name: 'phone', Icon: Phone, keywords: 'call โทรศัพท์ ติดต่อ' },
  { name: 'bell', Icon: Bell, keywords: 'notification กระดิ่ง แจ้งเตือน' },
  { name: 'calendar', Icon: Calendar, keywords: 'date schedule ปฏิทิน วันที่ นัด' },
  { name: 'clipboard', Icon: Clipboard, keywords: 'task คลิปบอร์ด งาน' },
  { name: 'clipboard-list', Icon: ClipboardList, keywords: 'task todo รายการ งาน เช็คลิสต์' },
  { name: 'check-circle-2', Icon: CheckCircle2, keywords: 'done complete เสร็จ ถูกต้อง' },
  { name: 'file-text', Icon: FileText, keywords: 'document doc เอกสาร ไฟล์' },
  { name: 'folder', Icon: Folder, keywords: 'folder โฟลเดอร์ แฟ้ม' },
  { name: 'folder-open', Icon: FolderOpen, keywords: 'folder โฟลเดอร์ แฟ้ม เปิด' },
  { name: 'bookmark', Icon: Bookmark, keywords: 'save บุ๊กมาร์ก คั่น' },
  { name: 'tag', Icon: Tag, keywords: 'label ป้าย แท็ก' },
  { name: 'tags', Icon: Tags, keywords: 'label ป้าย แท็ก หมวด' },
  { name: 'settings', Icon: Settings, keywords: 'config ตั้งค่า เฟือง' },
  { name: 'cog', Icon: Cog, keywords: 'config ตั้งค่า เฟือง ระบบ' },
  { name: 'wrench', Icon: Wrench, keywords: 'maintenance fix ซ่อม ดูแล บำรุง ประแจ' },
  { name: 'hammer', Icon: Hammer, keywords: 'build ก่อสร้าง ค้อน ซ่อม' },
  { name: 'ruler', Icon: Ruler, keywords: 'measure ไม้บรรทัด วัด' },
  { name: 'scissors', Icon: Scissors, keywords: 'cut กรรไกร ตัด' },
  { name: 'eye', Icon: Eye, keywords: 'view preview ดู ตา' },
  { name: 'search', Icon: Search, keywords: 'seo find ค้นหา แว่นขยาย' },
  { name: 'link-2', Icon: Link2, keywords: 'url link ลิงก์ เชื่อม' },
  { name: 'share-2', Icon: Share2, keywords: 'social share แชร์ แบ่งปัน' },
  { name: 'download', Icon: Download, keywords: 'download ดาวน์โหลด' },
  { name: 'upload', Icon: Upload, keywords: 'upload อัปโหลด' },
  { name: 'users', Icon: Users, keywords: 'team people ทีม คน ผู้ใช้' },
  { name: 'map', Icon: Map, keywords: 'map แผนที่' },
  { name: 'map-pin', Icon: MapPin, keywords: 'location หมุด สถานที่ ตำแหน่ง' },
  { name: 'compass', Icon: Compass, keywords: 'navigate เข็มทิศ ทิศทาง' },

  // ทั่วไป / ไลฟ์สไตล์
  { name: 'rocket', Icon: Rocket, keywords: 'launch startup จรวด เปิดตัว สตาร์ทอัพ' },
  { name: 'sparkles', Icon: Sparkles, keywords: 'new magic ใหม่ ประกาย พิเศษ' },
  { name: 'zap', Icon: Zap, keywords: 'fast energy เร็ว ไฟ พลัง' },
  { name: 'lightbulb', Icon: Lightbulb, keywords: 'idea ไอเดีย หลอดไฟ ความคิด' },
  { name: 'star', Icon: Star, keywords: 'favorite ดาว โปรด' },
  { name: 'heart', Icon: Heart, keywords: 'like love หัวใจ ชอบ' },
  { name: 'gift', Icon: Gift, keywords: 'present ของขวัญ โปรโมชัน' },
  { name: 'crown', Icon: Crown, keywords: 'premium vip มงกุฎ พรีเมียม' },
  { name: 'gem', Icon: Gem, keywords: 'premium jewelry เพชร อัญมณี พรีเมียม' },
  { name: 'flag', Icon: Flag, keywords: 'milestone ธง เป้า' },
  { name: 'sun', Icon: Sun, keywords: 'day light พระอาทิตย์ กลางวัน' },
  { name: 'moon', Icon: Moon, keywords: 'night dark พระจันทร์ กลางคืน' },
  { name: 'leaf', Icon: Leaf, keywords: 'eco green ใบไม้ ธรรมชาติ สิ่งแวดล้อม' },
  { name: 'trees', Icon: Trees, keywords: 'nature park ต้นไม้ ธรรมชาติ สวน' },
  { name: 'tree-pine', Icon: TreePine, keywords: 'nature ต้นสน ต้นไม้' },
  { name: 'flower-2', Icon: Flower2, keywords: 'flower ดอกไม้ สวน' },
  { name: 'paw-print', Icon: PawPrint, keywords: 'pet animal สัตว์ สัตว์เลี้ยง' },
  { name: 'baby', Icon: Baby, keywords: 'kids child เด็ก ทารก แม่และเด็ก' },
  { name: 'shirt', Icon: Shirt, keywords: 'fashion clothes เสื้อ แฟชั่น เสื้อผ้า' },
  { name: 'dumbbell', Icon: Dumbbell, keywords: 'gym fitness ฟิตเนส ออกกำลัง ยิม' },
  { name: 'stethoscope', Icon: Stethoscope, keywords: 'health doctor หมอ สุขภาพ การแพทย์' },
  { name: 'scale', Icon: Scale, keywords: 'law legal กฎหมาย ตราชั่ง ทนาย' },
  { name: 'anchor', Icon: Anchor, keywords: 'marine sea สมอ ทะเล เรือ' },
  { name: 'ship', Icon: Ship, keywords: 'shipping logistics เรือ ขนส่ง' },
  { name: 'plane', Icon: Plane, keywords: 'travel เครื่องบิน เดินทาง ทัวร์ ท่องเที่ยว' },
  { name: 'car', Icon: Car, keywords: 'auto vehicle รถ รถยนต์ ยานยนต์' },
  { name: 'bike', Icon: Bike, keywords: 'bicycle จักรยาน' },
  { name: 'bus', Icon: Bus, keywords: 'transport รถบัส รถเมล์ ขนส่ง' },
  { name: 'train', Icon: Train, keywords: 'transport รถไฟ ขนส่ง' },

  // อาหาร / เครื่องดื่ม
  { name: 'utensils', Icon: Utensils, keywords: 'food restaurant อาหาร ร้านอาหาร ช้อนส้อม' },
  { name: 'coffee', Icon: Coffee, keywords: 'cafe drink กาแฟ คาเฟ่ เครื่องดื่ม' },
  { name: 'pizza', Icon: Pizza, keywords: 'food พิซซ่า อาหาร' },
  { name: 'cake', Icon: Cake, keywords: 'bakery dessert เค้ก ขนม เบเกอรี่' },
  { name: 'croissant', Icon: Croissant, keywords: 'bakery ครัวซองต์ เบเกอรี่ ขนมปัง' },
  { name: 'ice-cream', Icon: IceCream, keywords: 'dessert ไอศกรีม ขนม หวาน' },
  { name: 'soup', Icon: Soup, keywords: 'food ซุป อาหาร' },
  { name: 'salad', Icon: Salad, keywords: 'healthy food สลัด อาหารคลีน ผัก' },
  { name: 'beef', Icon: Beef, keywords: 'meat food เนื้อ อาหาร' },
  { name: 'drumstick', Icon: Drumstick, keywords: 'chicken food ไก่ อาหาร' },
  { name: 'fish', Icon: Fish, keywords: 'seafood food ปลา อาหารทะเล' },
  { name: 'apple', Icon: Apple, keywords: 'fruit healthy แอปเปิล ผลไม้' },
  { name: 'carrot', Icon: Carrot, keywords: 'vegetable แครอท ผัก' },
  { name: 'wine', Icon: Wine, keywords: 'drink bar ไวน์ เหล้า บาร์' },
  { name: 'beer', Icon: Beer, keywords: 'drink bar เบียร์ บาร์' },
]

export const PROJECT_ICON_MAP: Record<string, LucideIcon> = Object.fromEntries(
  PROJECT_ICONS.map((i) => [i.name, i.Icon]),
)

/** ค้นไอคอนจากชื่อ + คีย์เวิร์ด (ไทย/อังกฤษ) — q ว่าง = คืนทั้งหมด */
export function searchIcons(q: string): ProjectIconDef[] {
  const s = q.trim().toLowerCase()
  if (!s) return PROJECT_ICONS
  return PROJECT_ICONS.filter((i) => i.name.includes(s) || i.keywords.toLowerCase().includes(s))
}
